### ISSUE TITLE
Accept rgb string as input

### ISSUE THREAD

**Issue by ozyman42** [russoedu/font-color-contrast#11]
If the input string is rgb, then filter it through a lib like https://www.npmjs.com/package/rgb-hex before computing the font color.
This way clients can assume any valid CSS color string is also a valid input to this lib and clients can avoid having logic in their own code which checks the color string's contents.

**Comment by russoedu** [comment]
Ts verification is already performed in many steps, both for string inputs and numeric inputs. The only thing is that when it fails a default value is returned (#ffffff) instead of an error.

I'll think of a way to see if it would be possible to return an error without breaking the existing API.
