### ISSUE TITLE
Cannot upgrade to v10 in typescript project

### ISSUE THREAD

**Issue by stephenkelzer** [russoedu/font-color-contrast#7]
I am currently on version `^1.1.1` in a typescript project. After updating the version to `10.0.0` in my package.json file and then running `yarn install` I get the following error:

```
error /node_modules/font-color-contrast: Command failed.
Exit code: 127
Command: tsc
Arguments: 
Directory: /node_modules/font-color-contrast
Output:

```

I have enjoyed this library so far and look forward to updating to the new version! Let me know if there is any more information that I can provide to help diagnose the issue, thank you!

**Comment by russoedu** [comment]
Thanks for the feedback, Stephen.

I’ll look at it and try to figure out why did tsc didn’t compile the app to js.

**Comment by stephenkelzer** [comment]
Thanks @russoedu !
Let me know if you need any info from me that would help

**Comment by russoedu** [comment]
Hi @stephenkelzer , I tried to look at it and apparently there's a conflict with some dependency version.

Can you try installing 10.0.1 and share the full output log?

**Comment by stephenkelzer** [comment]
Unfortunately, it does not seem to be working still. I even deleted my `node_modules` folder and deleted my `yarn.lock` file to see if that helped. Here is the full output when running the `yarn` command:
![image](https://user-images.githubusercontent.com/19741798/140330447-7892937b-017d-4133-8f84-fff4c38109ca.png)

I also cloned your repo and ran `npm run build` and everything worked fine doing that.

**Comment by stephenkelzer** [comment]
I have created a PR that seems to fix this for me: #8

**Comment by russoedu** [comment]
Hi @stephenkelzer , I believe this is now fixed and I now know what needs to be done to build TS packages. Thanks for the feedback!

**Comment by stephenkelzer** [comment]
Yay! It works now - thanks so much!
